#!/usr/bin/env groovy

println "Hello from Jenkinsfile!"

pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building.'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing.'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying.'
            }
        }
    }
}